services:
  - type: web
    name: trevonis
    runtime: node
    plan: starter
    autoDeploy: true
    buildCommand: bun install && bun run build
    startCommand: bun migrate && node dist/src/index.js
    envVars:
      - fromGroup: trevonis/bot
      - key: TZ
        value: Africa/Lagos
      - key: DATABASE_URL
        fromDatabase:
          name: trevonis
          property: connectionString
databases:
  - name: trevonis
    user: admin
    plan: basic-256mb
